name: Build and Publish @extrahorizon/exh-cli

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'

      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: yarn lint
      - run: yarn build
      - run: yarn test:ci

      - name: Determine version number and branch tag
        run: |
          package_version=$(node -p "require('./package.json').version")

          if [ "${{github.ref}}" == "refs/heads/master" ]
          then
            version_tag=$package_version
            branch_tag="latest"
          else
            if [ "${{github.ref}}" == "refs/heads/dev" ]
            then
              branch_tag="dev"
            else
              branch_tag="feat"
            fi
            sha=${{github.sha}}
            short_commit_hash=${sha:0:7}
            version_tag=$package_version-$branch_tag-${{github.run_number}}-$short_commit_hash
          fi

          echo "PROJECT_VERSION=$package_version" >> $GITHUB_ENV
          echo "VERSION_TAG=$version_tag" >> $GITHUB_ENV
          echo "BRANCH_TAG=$branch_tag" >> $GITHUB_ENV

      - name: Publish a git tag
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
          
          # Tag the commit with the correct version
          git tag -a $VERSION_TAG -m "Tagging $VERSION_TAG"
          git push origin $VERSION_TAG

      - name: Publish to the GitHub Packages registry
        run: yarn publish --new-version $VERSION_TAG --tag=$BRANCH_TAG
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: '@extrahorizon'

      - name: Publish to the NPM Registry
        run: yarn publish --new-version $VERSION_TAG --tag=$BRANCH_TAG
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_EXH_PUBLISH_TOKEN}}

      - name: Publish the json-schemas of the configuration files
        run: |
          if [ "${{github.ref}}" == "refs/heads/master" ]
          then
            documentation_version="${PROJECT_VERSION}"
          else
            documentation_version="${PROJECT_VERSION}-dev"
          fi

          aws s3 sync --delete ./src/config-json-schemas s3://swagger.extrahorizon.com/cli/${documentation_version}/config-json-schemas
          aws cloudfront create-invalidation --distribution-id E7MY46MSBV6S4 --paths /cli/${documentation_version}/*
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.CLI_SWAGGER_DOCS_DEPLOYER_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.CLI_SWAGGER_DOCS_DEPLOYER_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: eu-central-1
