name: Publish @extrahorizon/exh-cli

on:
  push:
    branches:
      - dev

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .npmrc
        run: |
          echo "@extrahorizon:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        